"const { add, multiply } = require('./utils.js');" 
"" 
"console.log('Hello Git!');" 
"console.log('5 + 3 =', add(5, 3));" 
"console.log('5 × 3 =', multiply(5, 3));" 
"" 
"// 新功能：数组处理" 
"const numbers = [1, 2, 3, 4, 5];" 
"const doubled = numbers.map(n => multiply(n, 2));" 
"console.log('翻倍数组:', doubled);" 
